### PR TITLE
I wanna be fabulous

### PR DESCRIPTION
**Pull request by 3ggs**
Pleeese lemme update my sit boi

### CODE REVIEW

**Comment by 3ggs** [comment]
Hello?

**Comment by 3ggs** [comment]
This branch has an updated version of my part of the site, this time much more cancerous including a rainbow background and a dumb animation for the buttons. This way people will gain twice as much cancer.

**Comment by Bak0n** [comment]
okie dokie

**Comment by 3ggs** [comment]
Yay

**Comment by 3ggs** [comment]
Now do an sh

**Pull request merged**
